// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Register struct {
	AccountName string `json:"accountName"`
	Password    string `json:"password"`
}

type NewGame struct {
	GameTitle             string            `json:"gameTitle"`
	GameDescription       string            `json:"gameDescription"`
	GamePrice             int               `json:"gamePrice"`
	GamePublisher         string            `json:"gamePublisher"`
	GameDeveloper         string            `json:"gameDeveloper"`
	GameTag               string            `json:"gameTag"`
	GameAdult             bool              `json:"gameAdult"`
	GameSystemRequirement string            `json:"gameSystemRequirement"`
	GameBanner            graphql.Upload    `json:"gameBanner"`
	GameSlideshow         []*graphql.Upload `json:"gameSlideshow"`
}

type NewPromo struct {
	GameID        int64     `json:"gameID"`
	DiscountPromo int       `json:"discountPromo"`
	EndDate       time.Time `json:"endDate"`
}

type UpdateGame struct {
	ID                    int64             `json:"id"`
	GameTitle             string            `json:"gameTitle"`
	GameDescription       string            `json:"gameDescription"`
	GamePrice             int               `json:"gamePrice"`
	GamePublisher         string            `json:"gamePublisher"`
	GameDeveloper         string            `json:"gameDeveloper"`
	GameTag               string            `json:"gameTag"`
	GameAdult             bool              `json:"gameAdult"`
	GameSystemRequirement string            `json:"gameSystemRequirement"`
	GameBanner            *graphql.Upload   `json:"gameBanner"`
	GameSlideshow         []*graphql.Upload `json:"gameSlideshow"`
}
